package Hibernate;
// Generated 03.12.2016 18:59:51 by Hibernate Tools 4.3.1

import java.time.LocalDateTime;





/**
 * Activity generated by hbm2java
 */
public class Activity  implements java.io.Serializable {


     private Integer activityId;
     private Category category;
     private String activityName;
     private String activityDescription;
     private LocalDateTime activityStartTime;
     private LocalDateTime activityEndTime;
     private Integer fkCategoryId;

    public Activity() {
    }

    public Activity(Category category, String activityName, String activityDescription, LocalDateTime activityStartTime, LocalDateTime activityEndTime, Integer fkCategoryId) {
       this.category = category;
       this.activityName = activityName;
       this.activityDescription = activityDescription;
       this.activityStartTime = activityStartTime;
       this.activityEndTime = activityEndTime;
       this.fkCategoryId = fkCategoryId;
    }
   
    public Integer getActivityId() {
        return this.activityId;
    }
    
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }
    public Category getCategory() {
        return this.category;
    }
    public void setCategory(Category category) {
        this.category = category;
    }
    
    public void setFkCategoryId(Integer fkCategoryId) {
        this.fkCategoryId = fkCategoryId; 
    }

    public Integer getFkCategoryId (){
        return this.fkCategoryId;
}
    
    public String getActivityName() {
        return this.activityName;
    }
    
    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }
    public String getActivityDescription() {
        return this.activityDescription;
    }
    
    public void setActivityDescription(String activityDescription) {
        this.activityDescription = activityDescription;
    }
    public LocalDateTime getActivityStartTime() {
        return this.activityStartTime;
    }
    
    public void setActivityStartTime(LocalDateTime activityStartTime) {
        this.activityStartTime = activityStartTime;
    }
    public LocalDateTime getActivityEndTime() {
        return this.activityEndTime;
    }
    
    public void setActivityEndTime(LocalDateTime activityEndTime) {
        this.activityEndTime = activityEndTime;
    }




}


